final freebies = [
  {
    'id': '0',
    'company': 'Starbucks',
    'type': 'Food & Drink',
    'free': true,
    'discount': false,
    'description': 'Free Food or Drink',
    'signup': true,
    'link': 'some url',
    'howto': 'Join Starbucks Rewards program',
    'valid': 'Only on your birthday',
  },
  {
    'id': '1',
    'company': 'Chatime',
    'type': 'Food & Drink',
    'free': true,
    'discount': false,
    'description': 'Free Birthday Drink',
    'signup': true,
    'link': 'some url',
    'howto': 'Register for Chatime Rewards',
    'valid': '7 days before and after birthday',
  },
  {
    'id': '2',
    'company': 'Sephora',
    'type': 'Cosmetics',
    'free': true,
    'discount': false,
    'description': 'Free Beauty Package',
    'signup': true,
    'link': 'some url',
    'howto': 'Sign up for Sephora Insider',
    'valid': 'Some range within your birthday',
  },
  {
    'id': '3',
    'company': 'Tim Hortons',
    'type': 'Food & Drink',
    'free': true,
    'discount': false,
    'description': 'Free Breakfast Sandwich or Drink',
    'signup': true,
    'link': 'some url',
    'howto': 'Tim Hortons App',
    'valid': '7 days before and after birthday',
  },
  {
    'id': '4',
    'company': 'The Body Shop',
    'type': 'Cosmetics',
    'free': true,
    'discount': false,
    'description': 'Free Gift Worth \$10',
    'signup': true,
    'link': 'some url',
    'howto': 'Join the Love Your Body club',
    'valid': 'Some range within your birthday',
  },
  {
    'id': '5',
    'company': 'Marble Slab Creamery',
    'type': 'Food & Drink',
    'free': true,
    'discount': false,
    'description': 'Free Ice Cream',
    'signup': true,
    'link': 'some url',
    'howto': 'Sign Up for Email Alerts',
    'valid': 'Day of your birthday',
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
];
