final freebies = [
  {
    'id': '0',
    'company': 'Starbucks',
    'type': 'Food & Drink',
    'gift': 'Free',
    'description': 'Free Food or Drink',
    'signup': true,
    'link': 'some url',
    'howto': 'Join Starbucks Rewards program',
    'valid': 'Only on your birthday',
    'notes': '',
  },
  {
    'id': '1',
    'company': 'Chatime',
    'type': 'Food & Drink',
    'gift': 'Free',
    'description': 'Free Birthday Drink',
    'signup': true,
    'link': 'some url',
    'howto': 'Register for Chatime Rewards',
    'valid': '7 days before and up to birthday',
    'notes': '',
  },
  {
    'id': '2',
    'company': 'Sephora',
    'type': 'Cosmetics',
    'gift': 'Free',
    'description': 'Free Beauty Package',
    'signup': true,
    'link': 'some url',
    'howto': 'Sign up for Sephora Insider',
    'valid': 'Some range within your birthday',
    'notes': '',
  },
  {
    'id': '3',
    'company': 'Tim Hortons',
    'type': 'Food & Drink',
    'gift': 'Free',
    'description': 'Free Breakfast Sandwich or Drink',
    'signup': true,
    'link': 'some url',
    'howto': 'Tim Hortons App',
    'valid': '7 days before and after birthday',
    'notes': '',
  },
  {
    'id': '4',
    'company': 'The Body Shop',
    'type': 'Cosmetics',
    'gift': 'Free',
    'description': 'Free Gift Worth \$10',
    'signup': true,
    'link': 'some url',
    'howto': 'Join the Love Your Body club',
    'valid': 'Some range within your birthday',
    'notes': '',
  },
  {
    'id': '5',
    'company': 'Marble Slab Creamery',
    'type': 'Food & Drink',
    'gift': 'Free',
    'description': 'Free Ice Cream',
    'signup': true,
    'link': 'some url',
    'howto': 'Sign Up for Email Alerts',
    'valid': 'Day of your birthday',
    'notes': '',
  },
  {
    'id': '6',
    'company': 'Denny\'s',
    'type': 'Food & Drink',
    'gift': 'Free',
    'description': 'Free "Build Your Own Grand Slam" Breakfast',
    'signup': false,
    'link': '',
    'howto': '',
    'valid': 'Only on your birthday',
    'notes': '',
  },
  {
    'id': '7',
    'company': 'iHalo Krunch',
    'type': 'Food & Drink',
    'gift': 'Free',
    'description': 'Free Ice Cream',
    'signup': false,
    'link': '',
    'howto': '',
    'valid': 'Only on your birthday',
    'notes': '',
  },
  {
    'id': '8',
    'company': 'What A Bagel',
    'type': 'Food & Drink',
    'gift': 'Bogo',
    'description': 'Get 6 Free Bagels when you buy 6',
    'signup': false,
    'link': '',
    'howto': '',
    'valid': 'Only on your birthday',
    'notes': '',
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
];
